# Generated by Django 5.0.3 on 2024-04-15 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorName', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'doctor_id must be exactly 8 digits')])),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.hospital')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.location'),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.location')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientName', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'patient_id must be exactly 14 digits')])),
                ('medical_information', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.location')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='available_departments',
            field=models.ManyToManyField(to='docApp.specialization'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bedStatus', models.CharField(default='unavailable')),
                ('bed_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.hospital')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.patient')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.specialization')),
            ],
        ),
    ]
