# Generated by Django 5.0.3 on 2024-04-15 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0002_doctor_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('clinic_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('available_slots', models.IntegerField(default=0)),
                ('booked_slots', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.clinic')),
            ],
        ),
    ]
