# Generated by Django 5.0.3 on 2024-04-15 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0003_remove_doctor_clinic_clinicschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='doctor_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'doctor_id must be exactly 8 digits')]),
        ),
    ]
