# Generated by Django 5.0.3 on 2024-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedStatus',
            field=models.CharField(default='unavailable', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
