# Generated by Django 5.0.3 on 2024-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_email_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorIMG',
            field=models.ImageField(blank=True, null=True, upload_to='DoctorIMG/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientIMG',
            field=models.ImageField(blank=True, null=True, upload_to='PatientIMG/'),
        ),
    ]
