# Generated by Django 5.0.3 on 2024-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_medical_information_patient_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomsStatus', models.CharField(default='unavailable', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='doctorName',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
