# Generated by Django 5.0.3 on 2024-04-30 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rooms_notification_age_notification_doctorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('related_doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'doctor_id must be exactly 8 digits')])),
            ],
        ),
    ]
