# Generated by Django 5.0.3 on 2024-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitalIMG',
            field=models.ImageField(blank=True, null=True, upload_to='HospitalIMG/'),
        ),
    ]
